/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/charts/Bar.vue')['default']
    BarChart: typeof import('./src/components/charts/BarChart.vue')['default']
    Doughnut: typeof import('./src/components/charts/Doughnut.vue')['default']
    DoughnutChart: typeof import('./src/components/charts/DoughnutChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LineChart: typeof import('./src/components/charts/LineChart.vue')['default']
    ProfileBlock: typeof import('./src/components/ProfileBlock.vue')['default']
    ProfileSearchHistory: typeof import('./src/components/ProfileSearchHistory.vue')['default']
    ReposTable: typeof import('./src/components/ReposTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsBlock: typeof import('./src/components/StatsBlock.vue')['default']
  }
}
