export type GithubUserType = {
  avatar_url: string;
  bio: string;
  blog: string;
  company: string;
  created_at: string;
  email: string;
  events_url: string;
  followers: number;
  followers_url: string;
  following: number;
  following_url: string;
  gists_url: string;
  gravatar_id: string;
  hireable: string;
  html_url: string;
  id: number;
  location: string;
  login: string;
  name: string;
  node_id: string;
  organizations_url: string;
  public_gists: number;
  public_repos: number;
  received_events_url: string;
  repos_url: string;
  site_admin: boolean;
  starred_url: string;
  subscriptions_url: string;
  twitter_username: string;
  type: string;
  updated_at: string;
  url: string;
};

export type GitHubRepoType = {
  created_at: string;
  description: string;
  fork: boolean;
  forks: number;
  forks_count: number;
  homepage: string;
  html_url: string;
  id: number;
  language: string;
  languages_url: string;
  name: string;
  open_issues: number;
  open_issues_count: number;
  size: number;
  stargazers_count: number;
  updated_at: string;
  url: string;
  watchers_count: number;
};

export type ProfileSearchHistoryType = {
  avatar_url: string;
  name: string;
  login: string;
  url: string;
};
